
@url = http://localhost:3000
@identity_provider = http://localhost:8080

###
# @name token
POST {{identity_provider}}/realms/provideremailgo/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=emailgo&username=leandro.tilio@gmail.com&password=123456&grant_type=password

###
@access_token = {{token.response.body.access_token}}

###
# @name campaign_create
POST {{url}}/campaigns
Authorization: Bearer {{access_token}}

{
	"name": "Teste API",
	"content": "TESTE DE API DE ENVIO DE EMAILS EM MASSA",
	"emails":  ["teste@email.com", "leandro.tilio@gmail.com"]
}

###

@campaign_id = {{campaign_create.response.body.id}}

###
GET {{url}}/ping

###
GET  {{url}}/campaigns/{{campaign_id}}
Authorization: Bearer {{access_token}}

###

DELETE {{url}}/campaigns/{{campaign_id}}
Authorization: Bearer {{access_token}}

###

PATCH  {{url}}/campaigns/{{campaign_id}}
Authorization: Bearer {{access_token}}

###
